name: Deploy via SSH on push to Main

on:
  push:
    branches:
      - main  # Adjust if using another branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trigger deploy.sh on server
        run: |
          ssh -o StrictHostKeyChecking=no -p 37980 ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} 'bash /var/www/main/deploy.sh'
