name: Deploy via SSH on push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH (fully mirrors manual behavior)
        run: |
          ssh -tt -o StrictHostKeyChecking=no -p 37980 root@103.120.48.189 '
            echo ">>> SSH connected"

            cd /var/www/main || exit 1

            # Force interactive shell behavior
            source ~/.bashrc >/dev/null 2>&1 || true
            source ~/.profile >/dev/null 2>&1 || true

            echo ">>> Starting deploy.sh"
            ./deploy.sh
            echo ">>> Done"
          '
